name: label-issue
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: label issue
        uses: andymckay/labeler@1.0.2
        with:
          add-labels: "major"
