name: install-netlify-package
on: [push]
jobs:
  check-netlify-version:
    runs-on: ubuntu-latest
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1
      # Install NodeJS
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # Run npm install and build on our code
      - run: npm install
      # Deploy to Netlify using our dev secrets
      - run: npm install netlify-cli -g
